export const AUTO_BATCH_PLSQL = `
DECLARE
  -- VARIABLES FOR API INPUT AND OUTPUT
  L_API_VERSION           NUMBER := 2.0; 
  L_VALIDATION_LEVEL      NUMBER := GME_COMMON_PVT.G_MAX_ERRORS; 
  L_INIT_MSG_LIST         VARCHAR2(1) := FND_API.G_TRUE; 
  L_COMMIT                VARCHAR2(1) := FND_API.G_FALSE; 
  L_MESSAGE_COUNT         NUMBER;
  L_MESSAGE_LIST          VARCHAR2(2000);
  L_RETURN_STATUS         VARCHAR2(1);
  L_BATCH_HEADER_REC      GME_BATCH_HEADER%ROWTYPE;
  L_BATCH_HEADER_OUT      GME_BATCH_HEADER%ROWTYPE;
  
  L_BATCH_SIZE            NUMBER := 100;
  L_BATCH_SIZE_UOM        VARCHAR2(3) := 'KG'; 
  L_CREATION_MODE         VARCHAR2(30) := 'RECIPE'; 
  L_RECIPE_NO             VARCHAR2(32); 
  L_RECIPE_VERSION        NUMBER; 
  L_RECIPE_ID             NUMBER := NULL; 
  L_PRODUCT_NO            VARCHAR2(32) := NULL; 
  L_PRODUCT_ID            NUMBER := NULL; 
  L_IGNORE_QTY_BELOW_CAP  VARCHAR2(1) := FND_API.G_TRUE; 
  L_USE_WORKDAY_CAL       VARCHAR2(1) := FND_API.G_FALSE; 
  L_CONTIGUITY_OVERRIDE   VARCHAR2(1) := FND_API.G_TRUE; 
  L_USE_LEAST_COST_VALIDITY_RULE VARCHAR2(1) := FND_API.G_FALSE; 
  L_EXCEPTION_MATERIAL_TBL GME_COMMON_PVT.EXCEPTIONS_TAB;
  L_MSG_INDEX_OUT NUMBER;

  P_USER_ID    VARCHAR2(15) := :user_id;
  P_RESP_ID    VARCHAR2(15) := '51637'; 
  P_RESP_APPL_ID VARCHAR2(20) := '552';
  P_PLAN_START   VARCHAR2(40) := :plan_start_date;
  P_ORG_CODE     VARCHAR2(4) := :org_code;
  P_BATCH_NAME   VARCHAR2(100) := :batch_name;
  
  l_retcode VARCHAR2(10) := '0';
  l_errbuf VARCHAR2(2000) := '';
  
CURSOR C_INF_BATCH IS
SELECT DISTINCT
          R.RECIPE_NO
          ,C.ROUTING_NO
          ,R.RECIPE_VERSION
          ,R.RECIPE_ID
          ,V.RECIPE_VALIDITY_RULE_ID
          ,V.ORGN_CODE
          ,V.RECIPE_USE
          ,V.PREFERENCE
          ,V.START_DATE
          ,V.END_DATE
          ,V.MIN_QTY
          ,V.MAX_QTY
          ,V.STD_QTY
          ,V.ITEM_UM
          ,NVL(D.PROMISEDAY,3) PROMISEDAY

FROM GMD_RECIPES R
,GMD_RECIPE_VALIDITY_RULES V
,GMD_ROUTINGS_B C
,SG_GME_BATCH_INF B
,SG_GME_BATCH_DAY D
WHERE R.RECIPE_ID=V.RECIPE_ID
AND C.ROUTING_ID = R.ROUTING_ID
AND R.RECIPE_STATUS = '700'
AND B.RECIPE_NO = R.RECIPE_NO
AND D.ROUTING(+) = C.ROUTING_NO
AND SUBSTR(B.RECIPE_VERSION,1,2) = TO_CHAR(R.RECIPE_VERSION)
AND V.RECIPE_USE = '0'
AND V.END_DATE IS NULL
AND R.RECIPE_STATUS = '700'
AND B.FLAG = 'N'  -- Only process new
AND B.BATCH_NAME = P_BATCH_NAME
AND V.PREFERENCE = '1'
ORDER BY
V.PREFERENCE;

BEGIN
  FOR V_INF_BATCH IN  C_INF_BATCH LOOP
    
  -- INITIALIZE THE SESSION
  FND_GLOBAL.APPS_INITIALIZE(
    USER_ID      => P_USER_ID, 
    RESP_ID      => P_RESP_ID,    
    RESP_APPL_ID => P_RESP_APPL_ID     
  );
  
  -- POPULATE BATCH HEADER RECORD
  L_BATCH_HEADER_REC.PLANT_CODE := P_ORG_CODE;
  L_BATCH_HEADER_REC.BATCH_NO := ''; -- LEAVE BLANK TO AUTO-GENERATE
  L_BATCH_HEADER_REC.BATCH_TYPE := 0; 
  L_BATCH_HEADER_REC.PLAN_START_DATE := TO_DATE(P_PLAN_START, 'YYYY/MM/DD HH24:MI:SS');
  L_BATCH_HEADER_REC.PLAN_CMPLT_DATE := TO_DATE(P_PLAN_START, 'YYYY/MM/DD HH24:MI:SS') + V_INF_BATCH.PROMISEDAY; 
  L_BATCH_HEADER_REC.DUE_DATE := TO_DATE(P_PLAN_START, 'YYYY/MM/DD HH24:MI:SS') + V_INF_BATCH.PROMISEDAY;
  L_BATCH_HEADER_REC.UPDATE_INVENTORY_IND := 'Y'; 
  L_BATCH_HEADER_REC.WIP_WHSE_CODE := P_ORG_CODE;
  L_BATCH_HEADER_REC.ATTRIBUTE1 := 'INTERFACE';
  L_BATCH_HEADER_REC.ATTRIBUTE2 := P_BATCH_NAME;
  L_BATCH_HEADER_REC.RECIPE_VALIDITY_RULE_ID := V_INF_BATCH.RECIPE_VALIDITY_RULE_ID ; 

  -- CALL THE CREATE_BATCH API
  GME_API_PUB.CREATE_BATCH(
    P_API_VERSION                 => L_API_VERSION,
    P_VALIDATION_LEVEL            => L_VALIDATION_LEVEL,
    P_INIT_MSG_LIST              => L_INIT_MSG_LIST,
    P_COMMIT                     => L_COMMIT,
    X_MESSAGE_COUNT              => L_MESSAGE_COUNT,
    X_MESSAGE_LIST               => L_MESSAGE_LIST,
    X_RETURN_STATUS              => L_RETURN_STATUS,
    P_ORG_CODE                   => P_ORG_CODE,
    P_BATCH_HEADER_REC           => L_BATCH_HEADER_REC,
    X_BATCH_HEADER_REC           => L_BATCH_HEADER_OUT,
    P_BATCH_SIZE                 => L_BATCH_SIZE,
    P_BATCH_SIZE_UOM             => L_BATCH_SIZE_UOM,
    P_CREATION_MODE              => L_CREATION_MODE,
    P_RECIPE_ID                  => V_INF_BATCH.RECIPE_ID,
    P_RECIPE_NO                  => V_INF_BATCH.RECIPE_NO,
    P_RECIPE_VERSION             => V_INF_BATCH.RECIPE_VERSION,
    P_PRODUCT_NO                 => L_PRODUCT_NO,
    P_PRODUCT_ID                 => L_PRODUCT_ID,
    P_IGNORE_QTY_BELOW_CAP       => L_IGNORE_QTY_BELOW_CAP,
    P_USE_WORKDAY_CAL            => L_USE_WORKDAY_CAL,
    P_CONTIGUITY_OVERRIDE        => L_CONTIGUITY_OVERRIDE,
    P_USE_LEAST_COST_VALIDITY_RULE => L_USE_LEAST_COST_VALIDITY_RULE,
    X_EXCEPTION_MATERIAL_TBL     => L_EXCEPTION_MATERIAL_TBL
  );

  -- HANDLE MESSAGES AND UPDATES
  IF L_RETURN_STATUS IN ('S', 'W', 'V') THEN
     UPDATE SG_GME_BATCH_INF 
     SET FLAG = 'Y', ERROR_MSG = NULL 
     WHERE RECIPE_NO = V_INF_BATCH.RECIPE_NO
     AND BATCH_NAME = P_BATCH_NAME
     AND SUBSTR(RECIPE_VERSION,1,2) = TO_CHAR(V_INF_BATCH.RECIPE_VERSION);
     COMMIT;
   ELSE
     l_retcode := '1';
     l_errbuf := '';
     IF L_MESSAGE_COUNT > 0 THEN
        FOR I IN 1..L_MESSAGE_COUNT LOOP
          FND_MSG_PUB.GET(
            P_MSG_INDEX     => I,
            P_DATA          => L_MESSAGE_LIST,
            P_MSG_INDEX_OUT => L_MSG_INDEX_OUT
          );
          l_errbuf := SUBSTR(l_errbuf || ' ' || L_MESSAGE_LIST, 1, 2000);
        END LOOP;
     ELSE
        l_errbuf := 'Unknown Error';
     END IF;
     
     l_errbuf := SUBSTR('Status: ' || L_RETURN_STATUS || ' Recipe: ' || V_INF_BATCH.RECIPE_NO || ' ' || l_errbuf, 1, 250);
     
     UPDATE SG_GME_BATCH_INF 
     SET FLAG = 'E', ERROR_MSG = l_errbuf
     WHERE RECIPE_NO = V_INF_BATCH.RECIPE_NO
     AND BATCH_NAME = P_BATCH_NAME 
     AND SUBSTR(RECIPE_VERSION,1,2) = TO_CHAR(V_INF_BATCH.RECIPE_VERSION);
     COMMIT;
  END IF;
END LOOP;

:x_retcode := l_retcode;
:x_errbuf := l_errbuf;

EXCEPTION
  WHEN OTHERS THEN
    :x_retcode := '2';
    :x_errbuf := SQLERRM;
END;
`;
